### ISSUE TITLE
[EPIC] Client notification

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#127]
## Description
This epic is meant to provide the client with meaningful realtime information about that could enhance the player gameplay, experience and immersion.

Most tasks are simply reacting to certain events by notifying the client of it. Tasks regarding ensuring a proper environment for such operations could be included

## Tasks
- [x] #116 Implement Phoenix.Channels
- [x] #117 Notify client when any process is finished
- [ ] #119 Broadcast change on server config
- [ ] #120 Broadcast file created/updated/deleted events to clients
- [x] #135 Broadcast when new log is created
- [x] #153 Server channel

**Comment by renatomassaro** [comment]
Fixed with Notificable
