### ISSUE TITLE
[EPIC] Basic moderation tools

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#128]
## Description
This epic is meant to provide the log user activity and provide the game moderators with adequate tooling to audit user history

## Tasks
- [ ] #110 React to account created event logging it for moderation purposes
- [ ] #113 React to account loggedin event logging it for moderation purposes
- [ ] #134 Log whenever an user installs a virus into a server
