### ISSUE TITLE
[EPIC] Improve File management functionality

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#129]
## Description
This epic is meant to improve the current functionality of the `software` domain, specifically on tasks and mechanics relating to file management.

## Tasks
- [x] #34 Adequate FileText as an specialization over File
- [x] #44 Create SoftwareAPI for File
- [ ] #83 Implement mapping of storage_id to server
- [ ] #84 Move (storage_id, drive_id) link from software to hardware
- [ ] #96 Validate File name
