### ISSUE TITLE
[EPIC] Network application and feature MVP

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#131]
## Description
This epic proposes to implement a minimum viable product for the Network application. It should make possible for processes to depend on the network/connection status and also allow the client to initiate those connections (and see them)

## Tasks
- [ ] #22 Improve TOP
- [x] #42 Create ProcessAPI
- [x] #94 Implement network related models
- [x] #97 Implement point-to-point connection
- [x] #100 Minimum event reaction on Network
- [ ] #101 Store connection id on process
- [x] #102 Implement TOP Manager
- [x] #112 Create Network API
- [ ] #121 Implement "child-processes"
- [ ] #122 Implement naive file download

**Comment by mememori** [comment]
Since this epic is closely tied to some spare tasks related to the `process` domain refactor and enhancement, i decided to merge them here as this epic explicitly depends on them
