### ISSUE TITLE
Sprint 1: Ground control to major Tom

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#132]
_Fun fact: on Lua and Erlang indexes start at 1\*_
_\* technically there is a single data structure on erlang that intends to implement array-like data structures that is exceptionally 0-index_

## Rationale
This sprint's main focus will be on ensuring that we have a 2-way transport method with the client. This can be achieved by issue #116.
By doing that same issue, we'll have a clear framework to implement the "websocket controllers" (channels implementation) so we can continue working on the public API without having to spend time on rework.

## Tasks
- [x] #116 Implement Phoenix.Channels (PR #151)
- [x] #153 Server channel (PR #167)
- [x] #117 Notify client when any process is finished (PR #173)
- ~#120 Broadcast file created/updated/deleted events to clients~
- [x] #135 Broadcast when new log is created
- [x] #101 Store connection id on process
- [x] #121 Implement "child-processes"
- [x] #122 Implement naive file download
- [x] #109 Emit event on account creation and use it to build bundle and to send email
- ~#154 Standardize returns from Websocket and HTTP~
- [x] #22 Improve TOP
- ~#118 Implement Server Config~
- ~#119 Broadcast change on server config~

## Workflow
![](http://i.imgur.com/9Cw9qP8.png)
```
digraph {
  splines="ortho";

  {node [shape=box color="#009933" fillcolor="#00BB445F" style="filled"]
    "#116"
    "#153"
    "#135"
    "#117"
    "#101"
    "#121"
    "#122"
    "#22"
    "#109"
  }

  {
    {rank=same;
      "#116"
    } ->
    {rank=same;
      "#153"
    } ->
    {rank=same;
      "#117" "#135"
    } ->
    {rank=same;
      "#101" "#121"
    } ->
    {rank=same;
      "#122"
    } ->
    {rank=same;
      "#22" "#109"
    } [style=invis]
  }

  {edge[weight=0.5 minlen=1 dir=none]
    "#116" -> "#153"

    "#153" -> "#117"
    "#153" -> "#135"

    "#101" -> "#122"

    "#121" -> "#122"
  }

  {edge[weight=0.1 color="#99999999" minlen=1 style=dashed]
    "#116" ->
    "#153" ->
    "#117" ->
    "#135" ->
    "#101" ->
    "#121" ->
    "#122" ->
    "#109" ->
    "#22"
  }
}
```

**Comment by mememori** [comment]
I'll remove from the scrum both #118 and #119 since "server config" is not essential and is basically useless without frontend support to dynamic backgrounds.

I'll also defer #109 as it is blocked by API improvements i'll be doing the next week
