### ISSUE TITLE
Pre-sprint warmup session

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#133]
_This technically is not a sprint per se since it was not planned before as such and i intend to add a few more stories in the middle of the week but it will be carried as such anyway_

## Tasks
- [x] #94 Implement network related models (PR #125)
- [x] #97 Implement point-to-point connection (PR #126)
- [x] #100 Minimum event reaction on Network (PR #137)
- [x] #112 Create Network API (PR #138)
- [x] #102 Implement TOP Manager (PR #147)
- [x] #42 Create ProcessAPI (PR #147)
- ~#121 Implement "child-processes"~
- ~#101 Store connection id on process~
- [x] #107 Logout endpoint (PR #141)
- [x] #130 Software File Controller's `get_files_on_target_storage` is not returning encrypted files (PR #142)
- [x] #44 Create SoftwareAPI for File (PR #143)
- ~#122 Implement naive file download~
- ~#109 Emit event on account creation and use it to build bundle and to send email~
- [X] #108 Remove POI from server (PR #146)
- [x] #13 Merge MotherboardSlot controller onto Motherboard controller (PR #145)
- [x] #34 Adequate FileText as an specialization over File (PR #149)
- [x] #140 Network Factory (PR #148)

## Dependency tree
![](http://i.imgur.com/EAMWwOc.png)
> Purple: @mememori
> Orange: @kress95 
```
digraph {
splines="ortho";

"#94 Implement network related models" [color=purple shape=polygon]
"#94 Implement network related models" -> "#97 Implement point-to-point connection"

"#97 Implement point-to-point connection" [color=purple shape=polygon]
"#97 Implement point-to-point connection" -> "#100 Minimum event reaction on Network"
"#97 Implement point-to-point connection" -> "#112 Create Network API"

"#100 Minimum event reaction on Network" [color=purple shape=polygon]
"#112 Create Network API" [color=purple shape=polygon]
"#102 Implement TOP Manager" [color=purple shape=polygon]
"#102 Implement TOP Manager" -> "#42 Create ProcessAPI"

"#42 Create ProcessAPI" [color=purple shape=polygon]

"#130 Software File Controller's ..." [color=orange shape=polygon]
"#130 Software File Controller's ..." -> "#44 Create SoftwareAPI for File"

"#44 Create SoftwareAPI for File" [color=orange shape=polygon]

"#108 Remove POI from server" [color=orange shape=polygon]

"#13 Merge MotherboardSlot controller onto Motherboard controller" [color=orange shape=polygon]

"#107 Logout endpoint" [color=orange shape=polygon]
"#34 Adequate FileText as an specialization over File" [color=orange shape=polygon]
"#140 Network Factory" [color=orange shape=polygon]

edge[style=invis]
"#108 Remove POI from server" -> "#107 Logout endpoint" -> "#140 Network Factory"
edge[style=invis]
"#13 Merge MotherboardSlot controller onto Motherboard controller" -> "#34 Adequate FileText as an specialization over File"
}

```

**Comment by mememori** [comment]
Going to remove "Refactor Process" (#22) from this _sprint_\* because it's underspecified, not planned, too broad and it'll make me have to work overtime to conclude as i am bloated with work todo already
