### ISSUE TITLE
HEBorn Closed Alpha feature planning

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#180]
![](http://i.imgur.com/ba8mOnm.png)

## Tasks
- [ ] #127 [EPIC] Client notification
- [ ] #129 [EPIC] Improve File management functionality
- [x] #131 [EPIC] Network application and feature MVP
- [ ] #156 [EPIC] Basic hacking
